### ISSUE TITLE
MM and mqtt

### ISSUE THREAD

**Issue by sergge1** [Anonym-tsk/MMM-HomeAssistant-MultiSensor#1]
@Anonym-tsk 
Николай, привествую!
Тебя увидел в теме по звуку к Amk2 модулю на magicmirror.
Я вижу ты в теме автоматизации.
Подскажи, у тебя работает что то в MM через mqtt протокол? 
Хочу хорошо подружить MM с остальным миром. 

Я вижу это как плагин к magicmirror, который 
1) слушает сообщения на брокере и транслирует их в Notifications MagicMirror (notification, payload) -  для того чтобы событиями из вне можно было управлять MM (например, запустить ютюб или гугл-ассистент тот же от какого-то события за пределами ММ)
2) И наоборот, допустим он обрабатывает Notifications ММ (например "MQTT_CLIENT") и пересылает их payload (со струкрутой {ветка:payload}) на mqtt брокер. У меня на ММ стоит датчик движения, и таким образом можно подвязать его к освещению в ванной легко.

Те плагины которые я видел - они просто отображают на экране инфо с mqtt сообщений. И то, запускается через раз.

**Comment by Anonym-tsk** [comment]
Привет. У меня в зеркале используется mqtt для включения/выключения экрана, подсветки и отправки статистики на брокер (cpu, mem, температура). Также получает с брокера некоторые команды (тот же свет, экран, перезагрузка и некоторые другие вещи). Но это все сделано в виде отдельного скрипта на питоне и от MM отвязано.
Лучше напиши в телеграм, могу рассказать подробнее - https://t.me/Vasilchuk
